# Remove these configuration records
# one by one as the offenses are removed from the code base.

# Offense count: 19
Metrics/AbcSize:
  Max: 46 # Goal: 15

# Offense count: 6
Metrics/CyclomaticComplexity:
  Max: 13

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 281

# Offense count: 6
Metrics/PerceivedComplexity:
  Max: 16

# Offense count: 33
Style/Documentation:
  Enabled: false

# Offense count: 2
Style/ModuleFunction:
  Exclude:
    - 'lib/paper_trail/serializers/json.rb'
    - 'lib/paper_trail/serializers/yaml.rb'
