# Remove these configuration records
# one by one as the offenses are removed from the code base.

# Offense count: 3
Lint/UnderscorePrefixedVariableName:
  Exclude:
    - 'lib/paper_trail/cleaner.rb'
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'lib/paper_trail/reifier.rb'

# Offense count: 12
# Cop supports --auto-correct.
# Configuration parameters: IgnoreEmptyBlocks.
Lint/UnusedBlockArgument:
  Exclude:
    - 'lib/paper_trail/cleaner.rb'
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'test/custom_json_serializer.rb'
    - 'test/unit/model_test.rb'
    - 'test/unit/serializer_test.rb'
    - 'test/unit/serializers/mixin_json_test.rb'
    - 'test/unit/serializers/mixin_yaml_test.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowUnusedKeywordArguments, IgnoreEmptyMethods.
Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'

# Offense count: 1
Lint/UselessAccessModifier:
  Exclude:
    - 'lib/paper_trail.rb'

# Offense count: 1
Lint/UselessAssignment:
  Exclude:
    - 'test/functional/controller_test.rb'

# Offense count: 1
Lint/Void:
  Exclude:
    - 'test/unit/cleaner_test.rb'

# Offense count: 19
Metrics/AbcSize:
  Max: 159

# Offense count: 1
Metrics/BlockNesting:
  Max: 5

# Offense count: 4
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 1106
  Exclude:
    - test/**/*

# Offense count: 6
Metrics/CyclomaticComplexity:
  Max: 13

# Offense count: 18
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 195

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 281

# Offense count: 6
Metrics/PerceivedComplexity:
  Max: 16

# Offense count: 1
# Cop supports --auto-correct.
Performance/RedundantBlockCall:
  Exclude:
    - 'lib/paper_trail/version_concern.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: MaxKeyValuePairs.
Performance/RedundantMerge:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'

# Offense count: 1
Style/AccessorMethodName:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'

# Offense count: 11
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: prefer_alias, prefer_alias_method
Style/Alias:
  Exclude:
    - 'lib/paper_trail.rb'
    - 'lib/paper_trail/config.rb'
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'lib/paper_trail/version_concern.rb'
    - 'test/dummy/app/models/song.rb'
    - 'test/unit/model_test.rb'

# Offense count: 10
# Cop supports --auto-correct.
# Configuration parameters: EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle, SupportedLastArgumentHashStyles.
# SupportedLastArgumentHashStyles: always_inspect, always_ignore, ignore_implicit, ignore_explicit
Style/AlignHash:
  Exclude:
    - 'lib/generators/paper_trail/install_generator.rb'
    - 'test/unit/model_test.rb'

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: with_first_parameter, with_fixed_indentation
Style/AlignParameters:
  Exclude:
    - 'doc/bug_report_template.rb'
    - 'lib/generators/paper_trail/templates/create_version_associations.rb'
    - 'lib/paper_trail/has_paper_trail.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: always, conditionals
Style/AndOr:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 44
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ProceduralMethods, FunctionalMethods, IgnoredMethods.
# SupportedStyles: line_count_based, semantic, braces_for_chaining
# ProceduralMethods: benchmark, bm, bmbm, create, each_with_object, measure, new, realtime, tap, with_object
# FunctionalMethods: let, let!, subject, watch
# IgnoredMethods: lambda, proc, it
Style/BlockDelimiters:
  Exclude:
    - 'doc/bug_report_template.rb'
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'lib/paper_trail/reifier.rb'
    - 'lib/paper_trail/version_concern.rb'
    - 'spec/models/skipper_spec.rb'
    - 'spec/models/widget_spec.rb'
    - 'test/unit/model_test.rb'
    - 'test/unit/version_test.rb'

# Offense count: 14
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: braces, no_braces, context_dependent
Style/BracesAroundHashParameters:
  Exclude:
    - 'test/functional/controller_test.rb'
    - 'test/functional/enabled_for_controller_test.rb'
    - 'test/unit/model_test.rb'

# Offense count: 3
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/functional/sinatra_test.rb'
    - 'test/test_helper.rb'
    - 'test/unit/model_test.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: is_a?, kind_of?
Style/ClassCheck:
  Exclude:
    - 'lib/paper_trail/frameworks/rspec.rb'

# Offense count: 3
# Cop supports --auto-correct.
Style/ColonMethodCall:
  Exclude:
    - 'test/unit/model_test.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: Keywords.
# Keywords: TODO, FIXME, OPTIMIZE, HACK, REVIEW
Style/CommentAnnotation:
  Exclude:
    - 'test/unit/model_test.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/CommentIndentation:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'test/functional/modular_sinatra_test.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: SingleLineConditionsOnly.
Style/ConditionalAssignment:
  Exclude:
    - 'test/dummy/app/controllers/articles_controller.rb'
    - 'test/dummy/app/controllers/widgets_controller.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/DeprecatedHashMethods:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'

# Offense count: 33
Style/Documentation:
  Enabled: false

# Offense count: 48
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: leading, trailing
Style/DotPosition:
  Enabled: false

# Offense count: 4
Style/DoubleNegation:
  Exclude:
    - 'lib/paper_trail.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowAdjacentOneLineDefs.
Style/EmptyLineBetweenDefs:
  Exclude:
    - 'test/dummy/app/models/song.rb'

# Offense count: 17
# Cop supports --auto-correct.
Style/EmptyLines:
  Exclude:
    - 'Rakefile'
    - 'test/unit/model_test.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/EmptyLinesAroundAccessModifier:
  Exclude:
    - 'lib/generators/paper_trail/install_generator.rb'

# Offense count: 14
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: empty_lines, no_empty_lines
Style/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/models/json_version_spec.rb'
    - 'spec/modules/version_concern_spec.rb'
    - 'spec/modules/version_number_spec.rb'
    - 'test/dummy/db/schema.rb'
    - 'test/functional/modular_sinatra_test.rb'
    - 'test/functional/sinatra_test.rb'
    - 'test/unit/cleaner_test.rb'
    - 'test/unit/model_test.rb'
    - 'test/unit/protected_attrs_test.rb'

# Offense count: 17
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: empty_lines, no_empty_lines
Style/EmptyLinesAroundClassBody:
  Exclude:
    - 'lib/generators/paper_trail/templates/add_object_changes_to_versions.rb'
    - 'lib/generators/paper_trail/templates/create_versions.rb'
    - 'lib/paper_trail/record_history.rb'
    - 'lib/paper_trail/reifier.rb'
    - 'test/dummy/app/controllers/widgets_controller.rb'
    - 'test/functional/enabled_for_controller_test.rb'
    - 'test/functional/sinatra_test.rb'
    - 'test/unit/cleaner_test.rb'
    - 'test/unit/model_test.rb'
    - 'test/unit/serializer_test.rb'
    - 'test/unit/serializers/json_test.rb'
    - 'test/unit/serializers/mixin_json_test.rb'
    - 'test/unit/serializers/mixin_yaml_test.rb'
    - 'test/unit/serializers/yaml_test.rb'
    - 'test/unit/timestamp_test.rb'

# Offense count: 6
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: empty_lines, no_empty_lines
Style/EmptyLinesAroundModuleBody:
  Exclude:
    - 'lib/paper_trail/frameworks/rails/controller.rb'
    - 'lib/paper_trail/frameworks/sinatra.rb'
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'lib/paper_trail/record_history.rb'
    - 'lib/paper_trail/reifier.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/EmptyLiteral:
  Exclude:
    - 'test/unit/model_test.rb'

# Offense count: 14
# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment, ForceEqualSignAlignment.
Style/ExtraSpacing:
  Exclude:
    - 'lib/generators/paper_trail/templates/create_versions.rb'
    - 'test/dummy/app/models/person.rb'
    - 'test/dummy/config.ru'
    - 'test/dummy/db/migrate/20110208155312_set_up_test_tables.rb'
    - 'test/dummy/db/schema.rb'
    - 'test/dummy/script/rails'
    - 'test/test_helper.rb'
    - 'test/unit/model_test.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: consistent, special_for_inner_method_call, special_for_inner_method_call_in_parentheses
Style/FirstParameterIndentation:
  Exclude:
    - 'lib/paper_trail/serializers/json.rb'

# Offense count: 606
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, UseHashRocketsWithSymbolValues.
# SupportedStyles: ruby19, ruby19_no_mixed_keys, hash_rockets
Style/HashSyntax:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Exclude:
    - 'test/dummy/config/application.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: special_inside_parentheses, consistent, align_braces
Style/IndentHash:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: Width.
Style/IndentationWidth:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'spec/models/widget_spec.rb'

# Offense count: 4
# Cop supports --auto-correct.
Style/Lambda:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'lib/paper_trail/version_concern.rb'
    - 'test/dummy/app/models/widget.rb'
    - 'test/unit/model_test.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/LeadingCommentSpace:
  Exclude:
    - 'test/unit/model_test.rb'

# Offense count: 6
# Cop supports --auto-correct.
Style/LineEndConcatenation:
  Exclude:
    - 'lib/generators/paper_trail/install_generator.rb'
    - 'lib/paper_trail.rb'
    - 'lib/paper_trail/config.rb'
    - 'lib/paper_trail/has_paper_trail.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: require_parentheses, require_no_parentheses, require_no_parentheses_except_multiline
Style/MethodDefParentheses:
  Enabled: false

# Offense count: 2
Style/ModuleFunction:
  Exclude:
    - 'lib/paper_trail/serializers/json.rb'
    - 'lib/paper_trail/serializers/yaml.rb'

# Offense count: 2
Style/MultilineBlockChain:
  Exclude:
    - 'lib/paper_trail/version_concern.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/MultilineBlockLayout:
  Exclude:
    - 'test/unit/model_test.rb'

# Offense count: 23
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: aligned, indented
Style/MultilineMethodCallIndentation:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: aligned, indented
Style/MultilineOperationIndentation:
  Enabled: false

# Offense count: 4
Style/MultilineTernaryOperator:
  Exclude:
    - 'lib/paper_trail/config.rb'
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'lib/paper_trail/reifier.rb'

# Offense count: 4
# Cop supports --auto-correct.
Style/MutableConstant:
  Exclude:
    - 'lib/generators/paper_trail/templates/create_versions.rb'
    - 'lib/paper_trail/version_number.rb'
    - 'test/dummy/app/models/widget.rb'
    - 'test/unit/associations_test.rb'

# Offense count: 1
Style/NestedParenthesizedCalls:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, MinBodyLength, SupportedStyles.
# SupportedStyles: skip_modifier_ifs, always
Style/Next:
  Exclude:
    - 'lib/paper_trail/reifier.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/Not:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 15

# Offense count: 4
# Cop supports --auto-correct.
Style/ParallelAssignment:
  Exclude:
    - 'spec/models/gadget_spec.rb'
    - 'test/test_helper.rb'

# Offense count: 6
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'spec/models/json_version_spec.rb'
    - 'spec/models/version_spec.rb'
    - 'test/unit/inheritance_column_test.rb'

# Offense count: 1
# Configuration parameters: NamePrefix, NamePrefixBlacklist, NameWhitelist.
# NamePrefix: is_, has_, have_
# NamePrefixBlacklist: is_, has_, have_
# NameWhitelist: is_a?
Style/PredicateName:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'

# Offense count: 6
# Cop supports --auto-correct.
Style/Proc:
  Exclude:
    - 'test/dummy/app/models/article.rb'
    - 'test/dummy/app/models/translation.rb'

# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: compact, exploded
Style/RaiseArgs:
  Enabled: false

# Offense count: 35
# Cop supports --auto-correct.
Style/RedundantSelf:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'lib/paper_trail/version_concern.rb'
    - 'test/dummy/app/models/article.rb'
    - 'test/unit/associations_test.rb'
    - 'test/unit/cleaner_test.rb'

# Offense count: 3
# Cop supports --auto-correct.
Style/RescueModifier:
  Exclude:
    - 'lib/paper_trail/version_concern.rb'
    - 'spec/models/version_spec.rb'
    - 'test/dummy/app/models/person.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: only_raise, only_fail, semantic
Style/SignalException:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'

# Offense count: 1
# Configuration parameters: Methods.
# Methods: {"reduce"=>["a", "e"]}, {"inject"=>["a", "e"]}
Style/SingleLineBlockParams:
  Exclude:
    - 'lib/paper_trail/reifier.rb'

# Offense count: 14
# Cop supports --auto-correct.
Style/SpaceAfterComma:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'test/custom_json_serializer.rb'
    - 'test/unit/cleaner_test.rb'
    - 'test/unit/model_test.rb'
    - 'test/unit/serializer_test.rb'
    - 'test/unit/serializers/mixin_json_test.rb'
    - 'test/unit/serializers/mixin_yaml_test.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: space, no_space
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment.
Style/SpaceAroundOperators:
  Exclude:
    - 'lib/paper_trail/frameworks/rails/controller.rb'
    - 'lib/paper_trail/frameworks/sinatra.rb'
    - 'spec/models/thing_spec.rb'
    - 'test/unit/cleaner_test.rb'
    - 'test/unit/serializer_test.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: space, no_space
Style/SpaceBeforeBlockBraces:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment.
Style/SpaceBeforeFirstArg:
  Exclude:
    - 'test/dummy/db/migrate/20110208155312_set_up_test_tables.rb'

# Offense count: 12
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
# SupportedStyles: space, no_space
Style/SpaceInsideBlockBraces:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/SpaceInsideBrackets:
  Exclude:
    - 'test/dummy/app/models/article.rb'

# Offense count: 26
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
# SupportedStyles: space, no_space
Style/SpaceInsideHashLiteralBraces:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/SpaceInsideParens:
  Exclude:
    - 'spec/models/widget_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: use_perl_names, use_english_names
Style/SpecialGlobalVars:
  Enabled: false

# Offense count: 519
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiteralsInInterpolation:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
# IgnoredMethods: respond_to
Style/SymbolProc:
  Exclude:
    - 'lib/paper_trail/reifier.rb'
    - 'test/unit/version_test.rb'

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: final_newline, final_blank_line
Style/TrailingBlankLines:
  Exclude:
    - 'lib/paper_trail/frameworks/active_record/models/paper_trail/version_association.rb'
    - 'spec/spec_helper.rb'
    - 'test/custom_json_serializer.rb'
    - 'test/dummy/app/models/thing.rb'
    - 'test/dummy/app/versions/post_version.rb'
    - 'test/dummy/config/boot.rb'
    - 'test/dummy/config/environments/development.rb'
    - 'test/test_helper.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline, SupportedStyles.
# SupportedStyles: comma, consistent_comma, no_comma
Style/TrailingCommaInLiteral:
  Exclude:
    - 'lib/paper_trail/frameworks/rails/controller.rb'

# Offense count: 3
# Cop supports --auto-correct.
Style/TrailingWhitespace:
  Exclude:
    - 'test/dummy/app/models/person.rb'
    - 'test/paper_trail_test.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: ExactNameMatch, AllowPredicates, AllowDSLWriters, IgnoreClassMethods, Whitelist.
# Whitelist: to_ary, to_a, to_c, to_enum, to_h, to_hash, to_i, to_int, to_io, to_open, to_path, to_proc, to_r, to_regexp, to_str, to_s, to_sym
Style/TrivialAccessors:
  Exclude:
    - 'test/dummy/app/controllers/application_controller.rb'

# Offense count: 1
Style/UnlessElse:
  Exclude:
    - 'lib/generators/paper_trail/install_generator.rb'

# Offense count: 13
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles, WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: percent
  MinSize: 4
