# Remove these configuration records
# one by one as the offenses are removed from the code base.

# Offense count: 19
Metrics/AbcSize:
  Max: 159

# Offense count: 1
Metrics/BlockNesting:
  Max: 5

# Offense count: 4
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 1106
  Exclude:
    - test/**/*

# Offense count: 6
Metrics/CyclomaticComplexity:
  Max: 13

# Offense count: 18
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 195

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 281

# Offense count: 6
Metrics/PerceivedComplexity:
  Max: 16

# Offense count: 1
Style/AccessorMethodName:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'

# Offense count: 11
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: prefer_alias, prefer_alias_method
Style/Alias:
  Exclude:
    - 'lib/paper_trail.rb'
    - 'lib/paper_trail/config.rb'
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'lib/paper_trail/version_concern.rb'
    - 'test/dummy/app/models/song.rb'
    - 'test/unit/model_test.rb'

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/unit/ar_id_map_test.rb'

# Offense count: 33
Style/Documentation:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: consistent, special_for_inner_method_call, special_for_inner_method_call_in_parentheses
Style/FirstParameterIndentation:
  Exclude:
    - 'lib/paper_trail/serializers/json.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Exclude:
    - 'test/dummy/config/application.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: special_inside_parentheses, consistent, align_braces
Style/IndentHash:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: Width.
Style/IndentationWidth:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'spec/models/widget_spec.rb'

# Offense count: 4
# Cop supports --auto-correct.
Style/Lambda:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'lib/paper_trail/version_concern.rb'
    - 'test/dummy/app/models/widget.rb'
    - 'test/unit/model_test.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/LeadingCommentSpace:
  Exclude:
    - 'test/unit/model_test.rb'

# Offense count: 6
# Cop supports --auto-correct.
Style/LineEndConcatenation:
  Exclude:
    - 'lib/generators/paper_trail/install_generator.rb'
    - 'lib/paper_trail.rb'
    - 'lib/paper_trail/config.rb'
    - 'lib/paper_trail/has_paper_trail.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: require_parentheses, require_no_parentheses, require_no_parentheses_except_multiline
Style/MethodDefParentheses:
  Enabled: false

# Offense count: 2
Style/ModuleFunction:
  Exclude:
    - 'lib/paper_trail/serializers/json.rb'
    - 'lib/paper_trail/serializers/yaml.rb'

# Offense count: 2
Style/MultilineBlockChain:
  Exclude:
    - 'lib/paper_trail/version_concern.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/MultilineBlockLayout:
  Exclude:
    - 'test/unit/model_test.rb'

# Offense count: 23
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: aligned, indented
Style/MultilineMethodCallIndentation:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: aligned, indented
Style/MultilineOperationIndentation:
  Enabled: false

# Offense count: 4
Style/MultilineTernaryOperator:
  Exclude:
    - 'lib/paper_trail/config.rb'
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'lib/paper_trail/reifier.rb'

# Offense count: 4
# Cop supports --auto-correct.
Style/MutableConstant:
  Exclude:
    - 'lib/generators/paper_trail/templates/create_versions.rb'
    - 'lib/paper_trail/version_number.rb'
    - 'test/dummy/app/models/widget.rb'
    - 'test/unit/associations_test.rb'

# Offense count: 1
Style/NestedParenthesizedCalls:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, MinBodyLength, SupportedStyles.
# SupportedStyles: skip_modifier_ifs, always
Style/Next:
  Exclude:
    - 'lib/paper_trail/reifier.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/Not:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 15

# Offense count: 4
# Cop supports --auto-correct.
Style/ParallelAssignment:
  Exclude:
    - 'spec/models/gadget_spec.rb'
    - 'test/test_helper.rb'

# Offense count: 6
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'spec/models/json_version_spec.rb'
    - 'spec/models/version_spec.rb'
    - 'test/unit/inheritance_column_test.rb'

# Offense count: 1
# Configuration parameters: NamePrefix, NamePrefixBlacklist, NameWhitelist.
# NamePrefix: is_, has_, have_
# NamePrefixBlacklist: is_, has_, have_
# NameWhitelist: is_a?
Style/PredicateName:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'

# Offense count: 6
# Cop supports --auto-correct.
Style/Proc:
  Exclude:
    - 'test/dummy/app/models/article.rb'
    - 'test/dummy/app/models/translation.rb'

# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: compact, exploded
Style/RaiseArgs:
  Enabled: false

# Offense count: 35
# Cop supports --auto-correct.
Style/RedundantSelf:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'lib/paper_trail/version_concern.rb'
    - 'test/dummy/app/models/article.rb'
    - 'test/unit/associations_test.rb'
    - 'test/unit/cleaner_test.rb'

# Offense count: 3
# Cop supports --auto-correct.
Style/RescueModifier:
  Exclude:
    - 'lib/paper_trail/version_concern.rb'
    - 'spec/models/version_spec.rb'
    - 'test/dummy/app/models/person.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: only_raise, only_fail, semantic
Style/SignalException:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'

# Offense count: 1
# Configuration parameters: Methods.
# Methods: {"reduce"=>["a", "e"]}, {"inject"=>["a", "e"]}
Style/SingleLineBlockParams:
  Exclude:
    - 'lib/paper_trail/reifier.rb'

# Offense count: 14
# Cop supports --auto-correct.
Style/SpaceAfterComma:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'test/custom_json_serializer.rb'
    - 'test/unit/cleaner_test.rb'
    - 'test/unit/model_test.rb'
    - 'test/unit/serializer_test.rb'
    - 'test/unit/serializers/mixin_json_test.rb'
    - 'test/unit/serializers/mixin_yaml_test.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: space, no_space
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment.
Style/SpaceAroundOperators:
  Exclude:
    - 'lib/paper_trail/frameworks/rails/controller.rb'
    - 'lib/paper_trail/frameworks/sinatra.rb'
    - 'spec/models/thing_spec.rb'
    - 'test/unit/cleaner_test.rb'
    - 'test/unit/serializer_test.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: space, no_space
Style/SpaceBeforeBlockBraces:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment.
Style/SpaceBeforeFirstArg:
  Exclude:
    - 'test/dummy/db/migrate/20110208155312_set_up_test_tables.rb'

# Offense count: 12
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
# SupportedStyles: space, no_space
Style/SpaceInsideBlockBraces:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/SpaceInsideBrackets:
  Exclude:
    - 'test/dummy/app/models/article.rb'

# Offense count: 26
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
# SupportedStyles: space, no_space
Style/SpaceInsideHashLiteralBraces:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/SpaceInsideParens:
  Exclude:
    - 'spec/models/widget_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: use_perl_names, use_english_names
Style/SpecialGlobalVars:
  Enabled: false

# Offense count: 519
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiteralsInInterpolation:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
# IgnoredMethods: respond_to
Style/SymbolProc:
  Exclude:
    - 'lib/paper_trail/reifier.rb'
    - 'test/unit/version_test.rb'
