language: ruby
cache: bundler

# For ruby, we test the highest and lowest minor versions only.
rvm:
  - 2.4
  - 2.7

env:
  global:
    - TRAVIS=true
  matrix:
    - DB=mysql
    - DB=postgres
    - DB=sqlite

# Travis recommend we use the VM infrastructure (`sudo: required`)
sudo: required

before_install:
  - gem update bundler

gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile
matrix:
  exclude:
    # rails 6 requires ruby >= 2.5.0
    - rvm: 2.4
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_6.1.gemfile
  fast_finish: true
services:
  - mysql
  - postgresql
