language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - ree
  - jruby-19mode
  - jruby-18mode
before_install:
  - gem install bundler --version '~> 1.3'
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: ree
