blank_issues_enabled: false
contact_links:
  - name: PaperTrail at StackOverflow
    url: https://stackoverflow.com/tags/paper-trail-gem
    about: Due to limited volunteers, we cannot answer usage questions on GitHub.
  - name: Security Vulnerabilities
    url: https://github.com/paper-trail-gem/paper_trail/blob/master/.github/CONTRIBUTING.md
    about: Please email jared@jaredbeck.com and batkinz@gmail.com.
